apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: messages-api-secrets
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: messages-api-secrets  # name of the Kubernetes Secret to be created
    creationPolicy: Owner
  # dataFrom extracts all keys of the JSON secret as individual Secret keys
  dataFrom:
    - extract:
        key: /itau-messages/production/app
